# ----------------------------------------
# Project specific properties
# ----------------------------------------
aetherwisp:
  volvox:
    application:
      browser-startup: false
      version: 1.0.0

# ----------------------------------------
# Common Application properties
# ----------------------------------------
logging:
   config: classpath:log4j2-dev.xml
server:
   port: 9876
spring:
  resources:
    cache:
      cachecontrol:
        cache-private: true
        must-revalidate: true
        no-store: true
    static-locations: file:src/main/resources/static/
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

