# ----------------------------------------
# Project specific properties
# ----------------------------------------
aetherwisp:
  volvox:
    application:
      scripts:
        adminlte: 3.0.2
        webfontloader: 1.6.28

# ----------------------------------------
# Common Application properties
# ----------------------------------------
server:
   servlet:
      context-path: /volvox
spring:
  mvc:
    favicon:
      enabled: true
  profiles:
    active: product
