# ----------------------------------------
# Project specific properties
# ----------------------------------------
aetherwisp:
  volvox:
    application:
      adminlte: 3.0.2

# ----------------------------------------
# Common Application properties
# ----------------------------------------
server:
   port: 9876
   servlet:
      context-path: /volvox

spring:
  mvc:
    favicon:
      enabled: true
  profiles:
    active: product
