# ----------------------------------------
# Project specific properties
# ----------------------------------------
aetherwisp:
  volvox:
    presentation:
      lib:
        axios:
          version: 0.21.0
        smartclient:
          version: v121p_2020-08-11
    application:
      browser-startup: true

# ----------------------------------------
# Common Application properties
# ----------------------------------------
server:
  compression:
    enabled: true
  servlet:
    context-path: /volvox
spring:
  mvc:
    favicon:
      enabled: true
  profiles:
    active: product
  resources:
    chain:
      # Jar ファイルに内包された GZip 済みリソースを使うようにする
      compressed: true
