# ----------------------------------------
# Project specific properties
# ----------------------------------------
aetherwisp:
  volvox:
    application:
      scripts:
        bootstrap: 4.5.0

# ----------------------------------------
# Common Application properties
# ----------------------------------------
server:
   servlet:
      context-path: /volvox
spring:
  mvc:
    favicon:
      enabled: true
  profiles:
    active: product
