# ----------------------------------------
# Spring Boot プロパティ
# ----------------------------------------
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/volvox
    username: postgres
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED
      maximum-pool-size: 10
      register-mbeans: false
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
