# ----------------------------------------
# Project specific properties
# ----------------------------------------
aetherwisp:
  volvox:
    webjars:
      smartclient:
        version: ${project.version}
